CREATE DATABASE IF NOT EXISTS GOLANG_MYSQL;
 
CREATE TABLE IF NOT EXISTS GOLANG_MYSQL.users(
id INT AUTO_INCREMENT,
name VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
PRIMARY KEY (id)
);

INSERT INTO users(name) VALUES ("Shin");

CREATE TABLE IF NOT EXISTS GOLANG_MYSQL.posts(
id INT AUTO_INCREMENT, 
title VARCHAR(100), 
user_id INT, 
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
PRIMARY KEY (id)
); 

INSERT INTO posts(title, user_id) VALUES("This is my first post!", 1);


